//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaysar_Mvc_DataBaseFirst_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customar()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int CustomarId { get; set; }
        public string CustomarName { get; set; }
        public string CustAddress { get; set; }
        public string CustMobile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
