//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaysar_Mvc_DataBaseFirst_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SalesId { get; set; }
        public int MemoNo { get; set; }
        public System.DateTime SalesDate { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public int ProductModelId { get; set; }
        public int CustomarId { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Customar Customar { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ProductModel ProductModel { get; set; }
    }
}
